#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# remove the default Nginx configure file
rm /etc/nginx/sites-enable/default
# Configure Nginx to listen o port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /ets/nginx/sites-enabled/default
# restart nginx
service nginx restart
